export const gradientChoices = [
  "bg-gradient-to-t",
  "bg-gradient-to-b",
  "bg-gradient-to-r",
  "bg-gradient-to-l",
  "bg-gradient-to-tl",
  "bg-gradient-to-tr",
  "bg-gradient-to-bl",
  "bg-gradient-to-br",
  // "bg-conic",
  // "bg-conic-to-b",
  // "bg-conic-to-bl",
  // "bg-conic-to-br",
  // "bg-conic-to-l",
  // "bg-conic-to-r",
  // "bg-conic-to-t",
  // "bg-conic-to-tl",
  // "bg-conic-to-tr",
  // "bg-radial",
  // "bg-radial-at-b",
  // "bg-radial-at-bl",
  // "bg-radial-at-br",
  // "bg-radial-at-l",
  // "bg-radial-at-r",
  // "bg-radial-at-t",
  // "bg-radial-at-tl",
  // "bg-radial-at-tr",
];

export const colorCombos = {
  cool: ["sky", "purple", "rose", "indigo", "violet", "pink"],
  warm: ["orange", "amber", "yellow", "red", "rose"],
  fresh: ["yellow", "lime", "emerald", "teal"],
  hip: ["fuchsia", "pink", "violet", "blue"],
  kaput: ["yellow", "pink", "blue"],
  blues: ["blue", "violet", "indigo", "sky"],
  sunset: ["red", "orange", "amber", "yellow"],
  green: ["green", "lime", "emerald"],
  RGB: ["green", "red", "blue"],
  pinky: ["pink", "rose", "violet"],
  redrose: ["red", "rose"],
};
